### ISSUE TITLE
Cant complete quiz

### ISSUE THREAD

**Issue by ScottDenton** [learn-co-curriculum/case-statements-readme#14]
Hello, I am unable to complete the quiz for this section.

The first question was already answered when I opened the page but It wont allow me to select any of the answers to the remainder of the questions either right or wrong ones.  Without being able to finish the quiz it continues to show as an incomplete section.

**Comment by sgharms** [comment]
This worked fine for me. For each question: select the appropriate answer(s). At right, the screen said "Completed" automatically. If this problem persists, please visit the following:

http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson
